import type {Metadata} from "next";
import {Geist, Geist_Mono, Inter, Jersey_10} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const gameFont = Jersey_10({
    variable: "--font-game",
    subsets: ["latin"],
    weight: ["400"]
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


/**
 * Root layout component that applies global fonts and wraps page content with the theme provider.
 *
 * @param children - The React nodes to render inside the layout's ThemeProvider.
 * @returns A JSX element representing the document root (<html> and <body>) with font CSS variables applied and the children wrapped by ThemeProvider configured with a default dark theme and system theme support.
 */
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${gameFont.variable} ${inter.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}